[character]
success_symbol = '[â¤](bold green) '
error_symbol = '[âŒ§](bold red) '

[hostname]
ssh_only = false
format = "(green bold)"
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ ğŸ•™ $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[directory]
truncation_length = 2
truncation_symbol = 'â€¦/'
home_symbol = 'ğŸ '

[cmd_duration]
disabled = true

[os.symbols]
Mint = "ğŸŒ¿ "

